### PR TITLE
Fix OpenComputers integration

### LINKED ISSUE #1254: Computer Controlled Seed Analyser not working with Open Computers
## Quick description
I have tried using the Computer Controlled Seed Analyser with Open Computers and it doesn't seem to be working, I have tried connecting the Computer up via an Adapter as well as having a robot sitting ontop of the block, but when I run "component.list()" in lua on the Computer, the CCSA doesn't show up.

## Mods and versions used
AgriCraft
OpenComputers

## Steps to replicate the issue
1. Setup OpenComputers computer or Robot
2. Place adapter next to CCSA or robot on top
3. Run lua -> component.list()

## Expectations and explanations
Trying to automate the breeding of seeds using the Computer Controlled Seed Analyser

## Your environment

* How are you playing?
  * Operating System: Windows 10
  * Launcher: Twitch Launcher
  * Modpack: Project Ozone 3
* What kind of server:
  * [X] Singleplayer
  * [X] Multiplayer
* Game Modes:
  * [X] Survival
  * [X] Creative
* Save File:
  * [X] Brand new save
  * [X] Only an existing save

## Links to crash logs, stack traces, etc
No Crash logs

### PR DESCRIPTION
**Pull request by josephcsible**
Fixes #1254.

### CODE REVIEW

**Comment by josephcsible** [comment]
Requires InfinityRaider/InfinityLib#31 to work.

**Comment by cenodis** [comment]
I tried building InfinityLib and Agricraft with the patches and replaced both in my copy of the MCEternal modpack. On startup it crashes instantly with an AbstractMethodError.

Crash Report: [https://clbin.com/M7lr8](https://clbin.com/M7lr8)

@josephcsible Could you maybe tell me whats going wrong here?

**Comment by josephcsible** [comment]
@cenodis AgriCraft isn't yet compatible with the git master version of InfinityLib, which it looks like you built. You need to instead apply the patch to the last released version of InfinityLib. You can get there by doing `git checkout a543fc2` to get the right version, and then `git cherry-pick 6770d65` to put just my patch on top of that.

**Comment by cenodis** [comment]
Now it works. Thank you

**Comment by InfinityRaider** [comment]
Rebase this on 1.12.2 branch and I will merge.

**Comment by josephcsible** [comment]
Done.

**Comment by InfinityRaider** [comment]
Thanks, the same holds for the InfinityLib PR.

**Pull request merged**
