### PR TITLE
Remove useless files

### PR DESCRIPTION
**Pull request by nbrichau**
I removed Thaumcraft & Ars Magica 2 textures, and the mcmod.info file.

I found also entity textures that I don't feel like they are used. But I didn't remove them as I was not sure. You tell me if I can.

### CODE REVIEW

**Comment by InfinityRaider** [comment]
I guess I could fetch them from the 1.12 branch if I'd ever need them again.

**Comment by nbrichau** [comment]
Well, Thaumcraft and Ars Magica 2 didn't update after 1.12 et never will, so you'll never have to fetch them.

**Comment by darthvader45** [comment]
Well, since TeamCoFH has the ability to dev Thaumcraft w/ Azanor having creative control over where it goes, it's possible Thaumcraft could eventually update past 1.12.  It's just not high on the priority list due to other stuff, including life.

**Comment by nbrichau** [comment]
King Lemming also said that we should assume it won't come out.

**Comment by darthvader45** [comment]
Yes, though he has teased things in the past.  Never say never, as they say.

**Comment by InfinityRaider** [comment]
This is not the place to discuss this, i am therefore locking the thread.

**Pull request merged**
