### PR TITLE
Add Environmental compatibility

### PR DESCRIPTION
**Pull request by nbrichau**

### CODE REVIEW

**Comment by InfinityRaider** [comment]
Botany Pots and IE recipe jsons seem to be missing.

**Comment by nbrichau** [comment]
Oh yeah, If forgot it was a thing. I'll add the recipes for the others mods too

**Comment by InfinityRaider** [comment]
Which other mods?
Perhaps I should merge the AgriPlants PR first, then you can use the tool I've written (or not, either way works).

**Comment by nbrichau** [comment]
I assumed for some reason that the mods currently compatible didn't had the recipes.
Nevermind what I said then.

**Pull request merged**
