### PR TITLE
Rename IAgriCrop methods with AbstractMethodErrors

### PR DESCRIPTION
**Pull request by CodesCubesAndCrashes**
Demonstration album: http://imgur.com/a/MvBJ6

For the IAgriCrop interface, this renames the getPos and getWorld
methods so as to not match the methods inherited from TileEntity.
The only uses so far were in the mutation strategies. And the newly
named methods just call the original named methods via 'this'.

This workaround is for a re-obfuscation bug in Special Source, a
program that ForgeGradle depends on.

https://github.com/MinecraftForge/ForgeGradle/issues/205
https://github.com/md-5/SpecialSource/issues/12

### CODE REVIEW

**Comment by CodesCubesAndCrashes** [comment]
Fixes #989

**Comment by RlonRyan** [comment]
This looks pretty good... I'm just debating what the methods should be named. It's tricky since the standard method names are taken, so...

I was kinda favoring getCropWorld() and getCropPos() given that the methods are inherited from the IAgriCrop interface. I think that the deobf part of the method name might be confusing to API users...

**Comment by CodesCubesAndCrashes** [comment]
The names weren't easy to pick. My choice was based on starting the same as `getWorld()` and `getPos()`, so that muscle memory and auto-complete would kick in. 

I'll switch them, your names are self explanatory at least. Thanks!

**Comment by RlonRyan** [comment]
I'm just going to make these changes on a commit directly applied to master to avoid all the merge stuff.

"Merged" in a roundabout way.

**Pull request closed without merging**
